# Generated by Django 3.2.18 on 2023-04-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_timesamp_datatable_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datatable',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='datatable',
            table='core_datatable',
        ),
    ]
